@startyaml
exchangePublicService:
	• exchangePublicService: ""
	loggerService: ""
	exchangeConnectionService:
		• exchangeConnectionService: ""
		loggerService: ""
		executionContextService: ""
		exchangeSchemaService:
			• exchangeSchemaService: ""
			loggerService: ""
		methodContextService: ""
strategyPublicService:
	• strategyPublicService: ""
	loggerService: ""
	strategyConnectionService:
		• strategyConnectionService: ""
		loggerService: ""
		executionContextService: ""
		strategySchemaService:
			• strategySchemaService: ""
			loggerService: ""
		exchangeConnectionService:
			• exchangeConnectionService: ""
			loggerService: ""
			executionContextService: ""
			exchangeSchemaService:
				• exchangeSchemaService: ""
				loggerService: ""
			methodContextService: ""
		methodContextService: ""
@endyaml