@startyaml
liveCommandService:
	• liveCommandService: ""
	loggerService:
		• loggerService: ""
		methodContextService: ""
		executionContextService: ""
	liveLogicPublicService:
		• liveLogicPublicService: ""
		loggerService:
			• loggerService: ""
			methodContextService: ""
			executionContextService: ""
		liveLogicPrivateService:
			• liveLogicPrivateService: ""
			loggerService:
				• loggerService: ""
				methodContextService: ""
				executionContextService: ""
			strategyCoreService:
				• strategyCoreService: ""
				loggerService:
					• loggerService: ""
					methodContextService: ""
					executionContextService: ""
				strategyConnectionService:
					• strategyConnectionService: ""
					loggerService:
						• loggerService: ""
						methodContextService: ""
						executionContextService: ""
					executionContextService: ""
					methodContextService: ""
					strategySchemaService:
						• strategySchemaService: ""
						loggerService:
							• loggerService: ""
							methodContextService: ""
							executionContextService: ""
					riskConnectionService:
						• riskConnectionService: ""
						loggerService:
							• loggerService: ""
							methodContextService: ""
							executionContextService: ""
						riskSchemaService:
							• riskSchemaService: ""
							loggerService:
								• loggerService: ""
								methodContextService: ""
								executionContextService: ""
						actionCoreService:
							• actionCoreService: ""
							loggerService:
								• loggerService: ""
								methodContextService: ""
								executionContextService: ""
							actionConnectionService:
								• actionConnectionService: ""
								loggerService:
									• loggerService: ""
									methodContextService: ""
									executionContextService: ""
								actionSchemaService:
									• actionSchemaService: ""
									loggerService:
										• loggerService: ""
										methodContextService: ""
										executionContextService: ""
							actionValidationService:
								• actionValidationService: ""
								loggerService:
									• loggerService: ""
									methodContextService: ""
									executionContextService: ""
							exchangeValidationService:
								• exchangeValidationService: ""
								loggerService:
									• loggerService: ""
									methodContextService: ""
									executionContextService: ""
							frameValidationService:
								• frameValidationService: ""
								loggerService:
									• loggerService: ""
									methodContextService: ""
									executionContextService: ""
							strategyValidationService:
								• strategyValidationService: ""
								loggerService:
									• loggerService: ""
									methodContextService: ""
									executionContextService: ""
								riskValidationService:
									• riskValidationService: ""
									loggerService:
										• loggerService: ""
										methodContextService: ""
										executionContextService: ""
								actionValidationService:
									• actionValidationService: ""
									loggerService:
										• loggerService: ""
										methodContextService: ""
										executionContextService: ""
							strategySchemaService:
								• strategySchemaService: ""
								loggerService:
									• loggerService: ""
									methodContextService: ""
									executionContextService: ""
							riskValidationService:
								• riskValidationService: ""
								loggerService:
									• loggerService: ""
									methodContextService: ""
									executionContextService: ""
					exchangeConnectionService:
						• exchangeConnectionService: ""
						loggerService:
							• loggerService: ""
							methodContextService: ""
							executionContextService: ""
						executionContextService: ""
						exchangeSchemaService:
							• exchangeSchemaService: ""
							loggerService:
								• loggerService: ""
								methodContextService: ""
								executionContextService: ""
						methodContextService: ""
					partialConnectionService:
						• partialConnectionService: ""
						loggerService:
							• loggerService: ""
							methodContextService: ""
							executionContextService: ""
						actionCoreService:
							• actionCoreService: ""
							loggerService:
								• loggerService: ""
								methodContextService: ""
								executionContextService: ""
							actionConnectionService:
								• actionConnectionService: ""
								loggerService:
									• loggerService: ""
									methodContextService: ""
									executionContextService: ""
								actionSchemaService:
									• actionSchemaService: ""
									loggerService:
										• loggerService: ""
										methodContextService: ""
										executionContextService: ""
							actionValidationService:
								• actionValidationService: ""
								loggerService:
									• loggerService: ""
									methodContextService: ""
									executionContextService: ""
							exchangeValidationService:
								• exchangeValidationService: ""
								loggerService:
									• loggerService: ""
									methodContextService: ""
									executionContextService: ""
							frameValidationService:
								• frameValidationService: ""
								loggerService:
									• loggerService: ""
									methodContextService: ""
									executionContextService: ""
							strategyValidationService:
								• strategyValidationService: ""
								loggerService:
									• loggerService: ""
									methodContextService: ""
									executionContextService: ""
								riskValidationService:
									• riskValidationService: ""
									loggerService:
										• loggerService: ""
										methodContextService: ""
										executionContextService: ""
								actionValidationService:
									• actionValidationService: ""
									loggerService:
										• loggerService: ""
										methodContextService: ""
										executionContextService: ""
							strategySchemaService:
								• strategySchemaService: ""
								loggerService:
									• loggerService: ""
									methodContextService: ""
									executionContextService: ""
							riskValidationService:
								• riskValidationService: ""
								loggerService:
									• loggerService: ""
									methodContextService: ""
									executionContextService: ""
					breakevenConnectionService:
						• breakevenConnectionService: ""
						loggerService:
							• loggerService: ""
							methodContextService: ""
							executionContextService: ""
						actionCoreService:
							• actionCoreService: ""
							loggerService:
								• loggerService: ""
								methodContextService: ""
								executionContextService: ""
							actionConnectionService:
								• actionConnectionService: ""
								loggerService:
									• loggerService: ""
									methodContextService: ""
									executionContextService: ""
								actionSchemaService:
									• actionSchemaService: ""
									loggerService:
										• loggerService: ""
										methodContextService: ""
										executionContextService: ""
							actionValidationService:
								• actionValidationService: ""
								loggerService:
									• loggerService: ""
									methodContextService: ""
									executionContextService: ""
							exchangeValidationService:
								• exchangeValidationService: ""
								loggerService:
									• loggerService: ""
									methodContextService: ""
									executionContextService: ""
							frameValidationService:
								• frameValidationService: ""
								loggerService:
									• loggerService: ""
									methodContextService: ""
									executionContextService: ""
							strategyValidationService:
								• strategyValidationService: ""
								loggerService:
									• loggerService: ""
									methodContextService: ""
									executionContextService: ""
								riskValidationService:
									• riskValidationService: ""
									loggerService:
										• loggerService: ""
										methodContextService: ""
										executionContextService: ""
								actionValidationService:
									• actionValidationService: ""
									loggerService:
										• loggerService: ""
										methodContextService: ""
										executionContextService: ""
							strategySchemaService:
								• strategySchemaService: ""
								loggerService:
									• loggerService: ""
									methodContextService: ""
									executionContextService: ""
							riskValidationService:
								• riskValidationService: ""
								loggerService:
									• loggerService: ""
									methodContextService: ""
									executionContextService: ""
					actionCoreService:
						• actionCoreService: ""
						loggerService:
							• loggerService: ""
							methodContextService: ""
							executionContextService: ""
						actionConnectionService:
							• actionConnectionService: ""
							loggerService:
								• loggerService: ""
								methodContextService: ""
								executionContextService: ""
							actionSchemaService:
								• actionSchemaService: ""
								loggerService:
									• loggerService: ""
									methodContextService: ""
									executionContextService: ""
						actionValidationService:
							• actionValidationService: ""
							loggerService:
								• loggerService: ""
								methodContextService: ""
								executionContextService: ""
						exchangeValidationService:
							• exchangeValidationService: ""
							loggerService:
								• loggerService: ""
								methodContextService: ""
								executionContextService: ""
						frameValidationService:
							• frameValidationService: ""
							loggerService:
								• loggerService: ""
								methodContextService: ""
								executionContextService: ""
						strategyValidationService:
							• strategyValidationService: ""
							loggerService:
								• loggerService: ""
								methodContextService: ""
								executionContextService: ""
							riskValidationService:
								• riskValidationService: ""
								loggerService:
									• loggerService: ""
									methodContextService: ""
									executionContextService: ""
							actionValidationService:
								• actionValidationService: ""
								loggerService:
									• loggerService: ""
									methodContextService: ""
									executionContextService: ""
						strategySchemaService:
							• strategySchemaService: ""
							loggerService:
								• loggerService: ""
								methodContextService: ""
								executionContextService: ""
						riskValidationService:
							• riskValidationService: ""
							loggerService:
								• loggerService: ""
								methodContextService: ""
								executionContextService: ""
				strategySchemaService:
					• strategySchemaService: ""
					loggerService:
						• loggerService: ""
						methodContextService: ""
						executionContextService: ""
				riskValidationService:
					• riskValidationService: ""
					loggerService:
						• loggerService: ""
						methodContextService: ""
						executionContextService: ""
				strategyValidationService:
					• strategyValidationService: ""
					loggerService:
						• loggerService: ""
						methodContextService: ""
						executionContextService: ""
					riskValidationService:
						• riskValidationService: ""
						loggerService:
							• loggerService: ""
							methodContextService: ""
							executionContextService: ""
					actionValidationService:
						• actionValidationService: ""
						loggerService:
							• loggerService: ""
							methodContextService: ""
							executionContextService: ""
				exchangeValidationService:
					• exchangeValidationService: ""
					loggerService:
						• loggerService: ""
						methodContextService: ""
						executionContextService: ""
				frameValidationService:
					• frameValidationService: ""
					loggerService:
						• loggerService: ""
						methodContextService: ""
						executionContextService: ""
			methodContextService: ""
	strategyValidationService:
		• strategyValidationService: ""
		loggerService:
			• loggerService: ""
			methodContextService: ""
			executionContextService: ""
		riskValidationService:
			• riskValidationService: ""
			loggerService:
				• loggerService: ""
				methodContextService: ""
				executionContextService: ""
		actionValidationService:
			• actionValidationService: ""
			loggerService:
				• loggerService: ""
				methodContextService: ""
				executionContextService: ""
	exchangeValidationService:
		• exchangeValidationService: ""
		loggerService:
			• loggerService: ""
			methodContextService: ""
			executionContextService: ""
	strategySchemaService:
		• strategySchemaService: ""
		loggerService:
			• loggerService: ""
			methodContextService: ""
			executionContextService: ""
	riskValidationService:
		• riskValidationService: ""
		loggerService:
			• loggerService: ""
			methodContextService: ""
			executionContextService: ""
	actionValidationService:
		• actionValidationService: ""
		loggerService:
			• loggerService: ""
			methodContextService: ""
			executionContextService: ""
backtestCommandService:
	• backtestCommandService: ""
	loggerService:
		• loggerService: ""
		methodContextService: ""
		executionContextService: ""
	strategySchemaService:
		• strategySchemaService: ""
		loggerService:
			• loggerService: ""
			methodContextService: ""
			executionContextService: ""
	riskValidationService:
		• riskValidationService: ""
		loggerService:
			• loggerService: ""
			methodContextService: ""
			executionContextService: ""
	actionValidationService:
		• actionValidationService: ""
		loggerService:
			• loggerService: ""
			methodContextService: ""
			executionContextService: ""
	backtestLogicPublicService:
		• backtestLogicPublicService: ""
		loggerService:
			• loggerService: ""
			methodContextService: ""
			executionContextService: ""
		backtestLogicPrivateService:
			• backtestLogicPrivateService: ""
			loggerService:
				• loggerService: ""
				methodContextService: ""
				executionContextService: ""
			strategyCoreService:
				• strategyCoreService: ""
				loggerService:
					• loggerService: ""
					methodContextService: ""
					executionContextService: ""
				strategyConnectionService:
					• strategyConnectionService: ""
					loggerService:
						• loggerService: ""
						methodContextService: ""
						executionContextService: ""
					executionContextService: ""
					methodContextService: ""
					strategySchemaService:
						• strategySchemaService: ""
						loggerService:
							• loggerService: ""
							methodContextService: ""
							executionContextService: ""
					riskConnectionService:
						• riskConnectionService: ""
						loggerService:
							• loggerService: ""
							methodContextService: ""
							executionContextService: ""
						riskSchemaService:
							• riskSchemaService: ""
							loggerService:
								• loggerService: ""
								methodContextService: ""
								executionContextService: ""
						actionCoreService:
							• actionCoreService: ""
							loggerService:
								• loggerService: ""
								methodContextService: ""
								executionContextService: ""
							actionConnectionService:
								• actionConnectionService: ""
								loggerService:
									• loggerService: ""
									methodContextService: ""
									executionContextService: ""
								actionSchemaService:
									• actionSchemaService: ""
									loggerService:
										• loggerService: ""
										methodContextService: ""
										executionContextService: ""
							actionValidationService:
								• actionValidationService: ""
								loggerService:
									• loggerService: ""
									methodContextService: ""
									executionContextService: ""
							exchangeValidationService:
								• exchangeValidationService: ""
								loggerService:
									• loggerService: ""
									methodContextService: ""
									executionContextService: ""
							frameValidationService:
								• frameValidationService: ""
								loggerService:
									• loggerService: ""
									methodContextService: ""
									executionContextService: ""
							strategyValidationService:
								• strategyValidationService: ""
								loggerService:
									• loggerService: ""
									methodContextService: ""
									executionContextService: ""
								riskValidationService:
									• riskValidationService: ""
									loggerService:
										• loggerService: ""
										methodContextService: ""
										executionContextService: ""
								actionValidationService:
									• actionValidationService: ""
									loggerService:
										• loggerService: ""
										methodContextService: ""
										executionContextService: ""
							strategySchemaService:
								• strategySchemaService: ""
								loggerService:
									• loggerService: ""
									methodContextService: ""
									executionContextService: ""
							riskValidationService:
								• riskValidationService: ""
								loggerService:
									• loggerService: ""
									methodContextService: ""
									executionContextService: ""
					exchangeConnectionService:
						• exchangeConnectionService: ""
						loggerService:
							• loggerService: ""
							methodContextService: ""
							executionContextService: ""
						executionContextService: ""
						exchangeSchemaService:
							• exchangeSchemaService: ""
							loggerService:
								• loggerService: ""
								methodContextService: ""
								executionContextService: ""
						methodContextService: ""
					partialConnectionService:
						• partialConnectionService: ""
						loggerService:
							• loggerService: ""
							methodContextService: ""
							executionContextService: ""
						actionCoreService:
							• actionCoreService: ""
							loggerService:
								• loggerService: ""
								methodContextService: ""
								executionContextService: ""
							actionConnectionService:
								• actionConnectionService: ""
								loggerService:
									• loggerService: ""
									methodContextService: ""
									executionContextService: ""
								actionSchemaService:
									• actionSchemaService: ""
									loggerService:
										• loggerService: ""
										methodContextService: ""
										executionContextService: ""
							actionValidationService:
								• actionValidationService: ""
								loggerService:
									• loggerService: ""
									methodContextService: ""
									executionContextService: ""
							exchangeValidationService:
								• exchangeValidationService: ""
								loggerService:
									• loggerService: ""
									methodContextService: ""
									executionContextService: ""
							frameValidationService:
								• frameValidationService: ""
								loggerService:
									• loggerService: ""
									methodContextService: ""
									executionContextService: ""
							strategyValidationService:
								• strategyValidationService: ""
								loggerService:
									• loggerService: ""
									methodContextService: ""
									executionContextService: ""
								riskValidationService:
									• riskValidationService: ""
									loggerService:
										• loggerService: ""
										methodContextService: ""
										executionContextService: ""
								actionValidationService:
									• actionValidationService: ""
									loggerService:
										• loggerService: ""
										methodContextService: ""
										executionContextService: ""
							strategySchemaService:
								• strategySchemaService: ""
								loggerService:
									• loggerService: ""
									methodContextService: ""
									executionContextService: ""
							riskValidationService:
								• riskValidationService: ""
								loggerService:
									• loggerService: ""
									methodContextService: ""
									executionContextService: ""
					breakevenConnectionService:
						• breakevenConnectionService: ""
						loggerService:
							• loggerService: ""
							methodContextService: ""
							executionContextService: ""
						actionCoreService:
							• actionCoreService: ""
							loggerService:
								• loggerService: ""
								methodContextService: ""
								executionContextService: ""
							actionConnectionService:
								• actionConnectionService: ""
								loggerService:
									• loggerService: ""
									methodContextService: ""
									executionContextService: ""
								actionSchemaService:
									• actionSchemaService: ""
									loggerService:
										• loggerService: ""
										methodContextService: ""
										executionContextService: ""
							actionValidationService:
								• actionValidationService: ""
								loggerService:
									• loggerService: ""
									methodContextService: ""
									executionContextService: ""
							exchangeValidationService:
								• exchangeValidationService: ""
								loggerService:
									• loggerService: ""
									methodContextService: ""
									executionContextService: ""
							frameValidationService:
								• frameValidationService: ""
								loggerService:
									• loggerService: ""
									methodContextService: ""
									executionContextService: ""
							strategyValidationService:
								• strategyValidationService: ""
								loggerService:
									• loggerService: ""
									methodContextService: ""
									executionContextService: ""
								riskValidationService:
									• riskValidationService: ""
									loggerService:
										• loggerService: ""
										methodContextService: ""
										executionContextService: ""
								actionValidationService:
									• actionValidationService: ""
									loggerService:
										• loggerService: ""
										methodContextService: ""
										executionContextService: ""
							strategySchemaService:
								• strategySchemaService: ""
								loggerService:
									• loggerService: ""
									methodContextService: ""
									executionContextService: ""
							riskValidationService:
								• riskValidationService: ""
								loggerService:
									• loggerService: ""
									methodContextService: ""
									executionContextService: ""
					actionCoreService:
						• actionCoreService: ""
						loggerService:
							• loggerService: ""
							methodContextService: ""
							executionContextService: ""
						actionConnectionService:
							• actionConnectionService: ""
							loggerService:
								• loggerService: ""
								methodContextService: ""
								executionContextService: ""
							actionSchemaService:
								• actionSchemaService: ""
								loggerService:
									• loggerService: ""
									methodContextService: ""
									executionContextService: ""
						actionValidationService:
							• actionValidationService: ""
							loggerService:
								• loggerService: ""
								methodContextService: ""
								executionContextService: ""
						exchangeValidationService:
							• exchangeValidationService: ""
							loggerService:
								• loggerService: ""
								methodContextService: ""
								executionContextService: ""
						frameValidationService:
							• frameValidationService: ""
							loggerService:
								• loggerService: ""
								methodContextService: ""
								executionContextService: ""
						strategyValidationService:
							• strategyValidationService: ""
							loggerService:
								• loggerService: ""
								methodContextService: ""
								executionContextService: ""
							riskValidationService:
								• riskValidationService: ""
								loggerService:
									• loggerService: ""
									methodContextService: ""
									executionContextService: ""
							actionValidationService:
								• actionValidationService: ""
								loggerService:
									• loggerService: ""
									methodContextService: ""
									executionContextService: ""
						strategySchemaService:
							• strategySchemaService: ""
							loggerService:
								• loggerService: ""
								methodContextService: ""
								executionContextService: ""
						riskValidationService:
							• riskValidationService: ""
							loggerService:
								• loggerService: ""
								methodContextService: ""
								executionContextService: ""
				strategySchemaService:
					• strategySchemaService: ""
					loggerService:
						• loggerService: ""
						methodContextService: ""
						executionContextService: ""
				riskValidationService:
					• riskValidationService: ""
					loggerService:
						• loggerService: ""
						methodContextService: ""
						executionContextService: ""
				strategyValidationService:
					• strategyValidationService: ""
					loggerService:
						• loggerService: ""
						methodContextService: ""
						executionContextService: ""
					riskValidationService:
						• riskValidationService: ""
						loggerService:
							• loggerService: ""
							methodContextService: ""
							executionContextService: ""
					actionValidationService:
						• actionValidationService: ""
						loggerService:
							• loggerService: ""
							methodContextService: ""
							executionContextService: ""
				exchangeValidationService:
					• exchangeValidationService: ""
					loggerService:
						• loggerService: ""
						methodContextService: ""
						executionContextService: ""
				frameValidationService:
					• frameValidationService: ""
					loggerService:
						• loggerService: ""
						methodContextService: ""
						executionContextService: ""
			exchangeCoreService:
				• exchangeCoreService: ""
				loggerService:
					• loggerService: ""
					methodContextService: ""
					executionContextService: ""
				exchangeConnectionService:
					• exchangeConnectionService: ""
					loggerService:
						• loggerService: ""
						methodContextService: ""
						executionContextService: ""
					executionContextService: ""
					exchangeSchemaService:
						• exchangeSchemaService: ""
						loggerService:
							• loggerService: ""
							methodContextService: ""
							executionContextService: ""
					methodContextService: ""
				methodContextService: ""
				exchangeValidationService:
					• exchangeValidationService: ""
					loggerService:
						• loggerService: ""
						methodContextService: ""
						executionContextService: ""
			frameCoreService:
				• frameCoreService: ""
				loggerService:
					• loggerService: ""
					methodContextService: ""
					executionContextService: ""
				frameConnectionService:
					• frameConnectionService: ""
					loggerService:
						• loggerService: ""
						methodContextService: ""
						executionContextService: ""
					frameSchemaService:
						• frameSchemaService: ""
						loggerService:
							• loggerService: ""
							methodContextService: ""
							executionContextService: ""
					methodContextService: ""
				frameValidationService:
					• frameValidationService: ""
					loggerService:
						• loggerService: ""
						methodContextService: ""
						executionContextService: ""
			methodContextService: ""
			actionCoreService:
				• actionCoreService: ""
				loggerService:
					• loggerService: ""
					methodContextService: ""
					executionContextService: ""
				actionConnectionService:
					• actionConnectionService: ""
					loggerService:
						• loggerService: ""
						methodContextService: ""
						executionContextService: ""
					actionSchemaService:
						• actionSchemaService: ""
						loggerService:
							• loggerService: ""
							methodContextService: ""
							executionContextService: ""
				actionValidationService:
					• actionValidationService: ""
					loggerService:
						• loggerService: ""
						methodContextService: ""
						executionContextService: ""
				exchangeValidationService:
					• exchangeValidationService: ""
					loggerService:
						• loggerService: ""
						methodContextService: ""
						executionContextService: ""
				frameValidationService:
					• frameValidationService: ""
					loggerService:
						• loggerService: ""
						methodContextService: ""
						executionContextService: ""
				strategyValidationService:
					• strategyValidationService: ""
					loggerService:
						• loggerService: ""
						methodContextService: ""
						executionContextService: ""
					riskValidationService:
						• riskValidationService: ""
						loggerService:
							• loggerService: ""
							methodContextService: ""
							executionContextService: ""
					actionValidationService:
						• actionValidationService: ""
						loggerService:
							• loggerService: ""
							methodContextService: ""
							executionContextService: ""
				strategySchemaService:
					• strategySchemaService: ""
					loggerService:
						• loggerService: ""
						methodContextService: ""
						executionContextService: ""
				riskValidationService:
					• riskValidationService: ""
					loggerService:
						• loggerService: ""
						methodContextService: ""
						executionContextService: ""
	strategyValidationService:
		• strategyValidationService: ""
		loggerService:
			• loggerService: ""
			methodContextService: ""
			executionContextService: ""
		riskValidationService:
			• riskValidationService: ""
			loggerService:
				• loggerService: ""
				methodContextService: ""
				executionContextService: ""
		actionValidationService:
			• actionValidationService: ""
			loggerService:
				• loggerService: ""
				methodContextService: ""
				executionContextService: ""
	exchangeValidationService:
		• exchangeValidationService: ""
		loggerService:
			• loggerService: ""
			methodContextService: ""
			executionContextService: ""
	frameValidationService:
		• frameValidationService: ""
		loggerService:
			• loggerService: ""
			methodContextService: ""
			executionContextService: ""
walkerCommandService:
	• walkerCommandService: ""
	loggerService:
		• loggerService: ""
		methodContextService: ""
		executionContextService: ""
	walkerLogicPublicService:
		• walkerLogicPublicService: ""
		loggerService:
			• loggerService: ""
			methodContextService: ""
			executionContextService: ""
		walkerLogicPrivateService:
			• walkerLogicPrivateService: ""
			loggerService:
				• loggerService: ""
				methodContextService: ""
				executionContextService: ""
			backtestLogicPublicService:
				• backtestLogicPublicService: ""
				loggerService:
					• loggerService: ""
					methodContextService: ""
					executionContextService: ""
				backtestLogicPrivateService:
					• backtestLogicPrivateService: ""
					loggerService:
						• loggerService: ""
						methodContextService: ""
						executionContextService: ""
					strategyCoreService:
						• strategyCoreService: ""
						loggerService:
							• loggerService: ""
							methodContextService: ""
							executionContextService: ""
						strategyConnectionService:
							• strategyConnectionService: ""
							loggerService:
								• loggerService: ""
								methodContextService: ""
								executionContextService: ""
							executionContextService: ""
							methodContextService: ""
							strategySchemaService:
								• strategySchemaService: ""
								loggerService:
									• loggerService: ""
									methodContextService: ""
									executionContextService: ""
							riskConnectionService:
								• riskConnectionService: ""
								loggerService:
									• loggerService: ""
									methodContextService: ""
									executionContextService: ""
								riskSchemaService:
									• riskSchemaService: ""
									loggerService:
										• loggerService: ""
										methodContextService: ""
										executionContextService: ""
								actionCoreService:
									• actionCoreService: ""
									loggerService:
										• loggerService: ""
										methodContextService: ""
										executionContextService: ""
									actionConnectionService:
										• actionConnectionService: ""
										loggerService:
											• loggerService: ""
											methodContextService: ""
											executionContextService: ""
										actionSchemaService:
											• actionSchemaService: ""
											loggerService:
												• loggerService: ""
												methodContextService: ""
												executionContextService: ""
									actionValidationService:
										• actionValidationService: ""
										loggerService:
											• loggerService: ""
											methodContextService: ""
											executionContextService: ""
									exchangeValidationService:
										• exchangeValidationService: ""
										loggerService:
											• loggerService: ""
											methodContextService: ""
											executionContextService: ""
									frameValidationService:
										• frameValidationService: ""
										loggerService:
											• loggerService: ""
											methodContextService: ""
											executionContextService: ""
									strategyValidationService:
										• strategyValidationService: ""
										loggerService:
											• loggerService: ""
											methodContextService: ""
											executionContextService: ""
										riskValidationService:
											• riskValidationService: ""
											loggerService:
												• loggerService: ""
												methodContextService: ""
												executionContextService: ""
										actionValidationService:
											• actionValidationService: ""
											loggerService:
												• loggerService: ""
												methodContextService: ""
												executionContextService: ""
									strategySchemaService:
										• strategySchemaService: ""
										loggerService:
											• loggerService: ""
											methodContextService: ""
											executionContextService: ""
									riskValidationService:
										• riskValidationService: ""
										loggerService:
											• loggerService: ""
											methodContextService: ""
											executionContextService: ""
							exchangeConnectionService:
								• exchangeConnectionService: ""
								loggerService:
									• loggerService: ""
									methodContextService: ""
									executionContextService: ""
								executionContextService: ""
								exchangeSchemaService:
									• exchangeSchemaService: ""
									loggerService:
										• loggerService: ""
										methodContextService: ""
										executionContextService: ""
								methodContextService: ""
							partialConnectionService:
								• partialConnectionService: ""
								loggerService:
									• loggerService: ""
									methodContextService: ""
									executionContextService: ""
								actionCoreService:
									• actionCoreService: ""
									loggerService:
										• loggerService: ""
										methodContextService: ""
										executionContextService: ""
									actionConnectionService:
										• actionConnectionService: ""
										loggerService:
											• loggerService: ""
											methodContextService: ""
											executionContextService: ""
										actionSchemaService:
											• actionSchemaService: ""
											loggerService:
												• loggerService: ""
												methodContextService: ""
												executionContextService: ""
									actionValidationService:
										• actionValidationService: ""
										loggerService:
											• loggerService: ""
											methodContextService: ""
											executionContextService: ""
									exchangeValidationService:
										• exchangeValidationService: ""
										loggerService:
											• loggerService: ""
											methodContextService: ""
											executionContextService: ""
									frameValidationService:
										• frameValidationService: ""
										loggerService:
											• loggerService: ""
											methodContextService: ""
											executionContextService: ""
									strategyValidationService:
										• strategyValidationService: ""
										loggerService:
											• loggerService: ""
											methodContextService: ""
											executionContextService: ""
										riskValidationService:
											• riskValidationService: ""
											loggerService:
												• loggerService: ""
												methodContextService: ""
												executionContextService: ""
										actionValidationService:
											• actionValidationService: ""
											loggerService:
												• loggerService: ""
												methodContextService: ""
												executionContextService: ""
									strategySchemaService:
										• strategySchemaService: ""
										loggerService:
											• loggerService: ""
											methodContextService: ""
											executionContextService: ""
									riskValidationService:
										• riskValidationService: ""
										loggerService:
											• loggerService: ""
											methodContextService: ""
											executionContextService: ""
							breakevenConnectionService:
								• breakevenConnectionService: ""
								loggerService:
									• loggerService: ""
									methodContextService: ""
									executionContextService: ""
								actionCoreService:
									• actionCoreService: ""
									loggerService:
										• loggerService: ""
										methodContextService: ""
										executionContextService: ""
									actionConnectionService:
										• actionConnectionService: ""
										loggerService:
											• loggerService: ""
											methodContextService: ""
											executionContextService: ""
										actionSchemaService:
											• actionSchemaService: ""
											loggerService:
												• loggerService: ""
												methodContextService: ""
												executionContextService: ""
									actionValidationService:
										• actionValidationService: ""
										loggerService:
											• loggerService: ""
											methodContextService: ""
											executionContextService: ""
									exchangeValidationService:
										• exchangeValidationService: ""
										loggerService:
											• loggerService: ""
											methodContextService: ""
											executionContextService: ""
									frameValidationService:
										• frameValidationService: ""
										loggerService:
											• loggerService: ""
											methodContextService: ""
											executionContextService: ""
									strategyValidationService:
										• strategyValidationService: ""
										loggerService:
											• loggerService: ""
											methodContextService: ""
											executionContextService: ""
										riskValidationService:
											• riskValidationService: ""
											loggerService:
												• loggerService: ""
												methodContextService: ""
												executionContextService: ""
										actionValidationService:
											• actionValidationService: ""
											loggerService:
												• loggerService: ""
												methodContextService: ""
												executionContextService: ""
									strategySchemaService:
										• strategySchemaService: ""
										loggerService:
											• loggerService: ""
											methodContextService: ""
											executionContextService: ""
									riskValidationService:
										• riskValidationService: ""
										loggerService:
											• loggerService: ""
											methodContextService: ""
											executionContextService: ""
							actionCoreService:
								• actionCoreService: ""
								loggerService:
									• loggerService: ""
									methodContextService: ""
									executionContextService: ""
								actionConnectionService:
									• actionConnectionService: ""
									loggerService:
										• loggerService: ""
										methodContextService: ""
										executionContextService: ""
									actionSchemaService:
										• actionSchemaService: ""
										loggerService:
											• loggerService: ""
											methodContextService: ""
											executionContextService: ""
								actionValidationService:
									• actionValidationService: ""
									loggerService:
										• loggerService: ""
										methodContextService: ""
										executionContextService: ""
								exchangeValidationService:
									• exchangeValidationService: ""
									loggerService:
										• loggerService: ""
										methodContextService: ""
										executionContextService: ""
								frameValidationService:
									• frameValidationService: ""
									loggerService:
										• loggerService: ""
										methodContextService: ""
										executionContextService: ""
								strategyValidationService:
									• strategyValidationService: ""
									loggerService:
										• loggerService: ""
										methodContextService: ""
										executionContextService: ""
									riskValidationService:
										• riskValidationService: ""
										loggerService:
											• loggerService: ""
											methodContextService: ""
											executionContextService: ""
									actionValidationService:
										• actionValidationService: ""
										loggerService:
											• loggerService: ""
											methodContextService: ""
											executionContextService: ""
								strategySchemaService:
									• strategySchemaService: ""
									loggerService:
										• loggerService: ""
										methodContextService: ""
										executionContextService: ""
								riskValidationService:
									• riskValidationService: ""
									loggerService:
										• loggerService: ""
										methodContextService: ""
										executionContextService: ""
						strategySchemaService:
							• strategySchemaService: ""
							loggerService:
								• loggerService: ""
								methodContextService: ""
								executionContextService: ""
						riskValidationService:
							• riskValidationService: ""
							loggerService:
								• loggerService: ""
								methodContextService: ""
								executionContextService: ""
						strategyValidationService:
							• strategyValidationService: ""
							loggerService:
								• loggerService: ""
								methodContextService: ""
								executionContextService: ""
							riskValidationService:
								• riskValidationService: ""
								loggerService:
									• loggerService: ""
									methodContextService: ""
									executionContextService: ""
							actionValidationService:
								• actionValidationService: ""
								loggerService:
									• loggerService: ""
									methodContextService: ""
									executionContextService: ""
						exchangeValidationService:
							• exchangeValidationService: ""
							loggerService:
								• loggerService: ""
								methodContextService: ""
								executionContextService: ""
						frameValidationService:
							• frameValidationService: ""
							loggerService:
								• loggerService: ""
								methodContextService: ""
								executionContextService: ""
					exchangeCoreService:
						• exchangeCoreService: ""
						loggerService:
							• loggerService: ""
							methodContextService: ""
							executionContextService: ""
						exchangeConnectionService:
							• exchangeConnectionService: ""
							loggerService:
								• loggerService: ""
								methodContextService: ""
								executionContextService: ""
							executionContextService: ""
							exchangeSchemaService:
								• exchangeSchemaService: ""
								loggerService:
									• loggerService: ""
									methodContextService: ""
									executionContextService: ""
							methodContextService: ""
						methodContextService: ""
						exchangeValidationService:
							• exchangeValidationService: ""
							loggerService:
								• loggerService: ""
								methodContextService: ""
								executionContextService: ""
					frameCoreService:
						• frameCoreService: ""
						loggerService:
							• loggerService: ""
							methodContextService: ""
							executionContextService: ""
						frameConnectionService:
							• frameConnectionService: ""
							loggerService:
								• loggerService: ""
								methodContextService: ""
								executionContextService: ""
							frameSchemaService:
								• frameSchemaService: ""
								loggerService:
									• loggerService: ""
									methodContextService: ""
									executionContextService: ""
							methodContextService: ""
						frameValidationService:
							• frameValidationService: ""
							loggerService:
								• loggerService: ""
								methodContextService: ""
								executionContextService: ""
					methodContextService: ""
					actionCoreService:
						• actionCoreService: ""
						loggerService:
							• loggerService: ""
							methodContextService: ""
							executionContextService: ""
						actionConnectionService:
							• actionConnectionService: ""
							loggerService:
								• loggerService: ""
								methodContextService: ""
								executionContextService: ""
							actionSchemaService:
								• actionSchemaService: ""
								loggerService:
									• loggerService: ""
									methodContextService: ""
									executionContextService: ""
						actionValidationService:
							• actionValidationService: ""
							loggerService:
								• loggerService: ""
								methodContextService: ""
								executionContextService: ""
						exchangeValidationService:
							• exchangeValidationService: ""
							loggerService:
								• loggerService: ""
								methodContextService: ""
								executionContextService: ""
						frameValidationService:
							• frameValidationService: ""
							loggerService:
								• loggerService: ""
								methodContextService: ""
								executionContextService: ""
						strategyValidationService:
							• strategyValidationService: ""
							loggerService:
								• loggerService: ""
								methodContextService: ""
								executionContextService: ""
							riskValidationService:
								• riskValidationService: ""
								loggerService:
									• loggerService: ""
									methodContextService: ""
									executionContextService: ""
							actionValidationService:
								• actionValidationService: ""
								loggerService:
									• loggerService: ""
									methodContextService: ""
									executionContextService: ""
						strategySchemaService:
							• strategySchemaService: ""
							loggerService:
								• loggerService: ""
								methodContextService: ""
								executionContextService: ""
						riskValidationService:
							• riskValidationService: ""
							loggerService:
								• loggerService: ""
								methodContextService: ""
								executionContextService: ""
			backtestMarkdownService:
				• backtestMarkdownService: ""
				loggerService:
					• loggerService: ""
					methodContextService: ""
					executionContextService: ""
			walkerSchemaService:
				• walkerSchemaService: ""
				loggerService:
					• loggerService: ""
					methodContextService: ""
					executionContextService: ""
		walkerSchemaService:
			• walkerSchemaService: ""
			loggerService:
				• loggerService: ""
				methodContextService: ""
				executionContextService: ""
	walkerSchemaService:
		• walkerSchemaService: ""
		loggerService:
			• loggerService: ""
			methodContextService: ""
			executionContextService: ""
	strategyValidationService:
		• strategyValidationService: ""
		loggerService:
			• loggerService: ""
			methodContextService: ""
			executionContextService: ""
		riskValidationService:
			• riskValidationService: ""
			loggerService:
				• loggerService: ""
				methodContextService: ""
				executionContextService: ""
		actionValidationService:
			• actionValidationService: ""
			loggerService:
				• loggerService: ""
				methodContextService: ""
				executionContextService: ""
	exchangeValidationService:
		• exchangeValidationService: ""
		loggerService:
			• loggerService: ""
			methodContextService: ""
			executionContextService: ""
	frameValidationService:
		• frameValidationService: ""
		loggerService:
			• loggerService: ""
			methodContextService: ""
			executionContextService: ""
	walkerValidationService:
		• walkerValidationService: ""
		loggerService:
			• loggerService: ""
			methodContextService: ""
			executionContextService: ""
	strategySchemaService:
		• strategySchemaService: ""
		loggerService:
			• loggerService: ""
			methodContextService: ""
			executionContextService: ""
	riskValidationService:
		• riskValidationService: ""
		loggerService:
			• loggerService: ""
			methodContextService: ""
			executionContextService: ""
	actionValidationService:
		• actionValidationService: ""
		loggerService:
			• loggerService: ""
			methodContextService: ""
			executionContextService: ""
@endyaml